// Base d'exercices dérivée de Free Exercise DB (yuhonas/free-exercise-db, licence Unlicense / domaine public)
// https://github.com/yuhonas/free-exercise-db
import type { Exercise } from '../types'

export const FREE_EXERCISE_DB: Exercise[] = [
  { id: '3-4-sit-up', name: '3/4 Sit-Up', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'ab-crunch-machine', name: 'Ab Crunch Machine', muscleGroup: 'Abdominaux', equipment: 'Machine' },
  { id: 'ab-roller', name: 'Ab Roller', muscleGroup: 'Abdominaux', equipment: 'Autre' },
  { id: 'advanced-kettlebell-windmill', name: 'Advanced Kettlebell Windmill', muscleGroup: 'Abdominaux', equipment: 'Kettlebell' },
  { id: 'air-bike', name: 'Air Bike', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'alternate-heel-touchers', name: 'Alternate Heel Touchers', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'barbell-ab-rollout', name: 'Barbell Ab Rollout', muscleGroup: 'Abdominaux', equipment: 'Barre' },
  { id: 'barbell-ab-rollout-on-knees', name: 'Barbell Ab Rollout - On Knees', muscleGroup: 'Abdominaux', equipment: 'Barre' },
  { id: 'barbell-rollout-from-bench', name: 'Barbell Rollout from Bench', muscleGroup: 'Abdominaux', equipment: 'Barre' },
  { id: 'barbell-side-bend', name: 'Barbell Side Bend', muscleGroup: 'Abdominaux', equipment: 'Barre' },
  { id: 'bent-press', name: 'Bent Press', muscleGroup: 'Abdominaux', equipment: 'Kettlebell' },
  { id: 'bent-knee-hip-raise', name: 'Bent-Knee Hip Raise', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'bosu-ball-cable-crunch-with-side-bends', name: 'Bosu Ball Cable Crunch With Side Bends', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'bottoms-up', name: 'Bottoms Up', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'butt-ups', name: 'Butt-Ups', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'cable-judo-flip', name: 'Cable Judo Flip', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'cable-reverse-crunch', name: 'Cable Reverse Crunch', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'cable-russian-twists', name: 'Cable Russian Twists', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'cable-seated-crunch', name: 'Cable Seated Crunch', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'cocoons', name: 'Cocoons', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'cross-body-crunch', name: 'Cross-Body Crunch', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'crunch-hands-overhead', name: 'Crunch - Hands Overhead', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'crunch-legs-on-exercise-ball', name: 'Crunch - Legs On Exercise Ball', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'crunches', name: 'Crunches', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'dead-bug', name: 'Dead Bug', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'decline-crunch', name: 'Decline Crunch', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'decline-oblique-crunch', name: 'Decline Oblique Crunch', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'decline-reverse-crunch', name: 'Decline Reverse Crunch', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'double-kettlebell-windmill', name: 'Double Kettlebell Windmill', muscleGroup: 'Abdominaux', equipment: 'Kettlebell' },
  { id: 'dumbbell-side-bend', name: 'Dumbbell Side Bend', muscleGroup: 'Abdominaux', equipment: 'Haltères' },
  { id: 'elbow-to-knee', name: 'Elbow to Knee', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'exercise-ball-crunch', name: 'Exercise Ball Crunch', muscleGroup: 'Abdominaux', equipment: 'Swiss ball' },
  { id: 'exercise-ball-pull-in', name: 'Exercise Ball Pull-In', muscleGroup: 'Abdominaux', equipment: 'Swiss ball' },
  { id: 'flat-bench-leg-pull-in', name: 'Flat Bench Leg Pull-In', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'flat-bench-lying-leg-raise', name: 'Flat Bench Lying Leg Raise', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'frog-sit-ups', name: 'Frog Sit-Ups', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'gorilla-chin-crunch', name: 'Gorilla Chin/Crunch', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'hanging-pike', name: 'Hanging Pike', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'jackknife-sit-up', name: 'Jackknife Sit-Up', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'janda-sit-up', name: 'Janda Sit-Up', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'kettlebell-figure-8', name: 'Kettlebell Figure 8', muscleGroup: 'Abdominaux', equipment: 'Kettlebell' },
  { id: 'kettlebell-pass-between-the-legs', name: 'Kettlebell Pass Between The Legs', muscleGroup: 'Abdominaux', equipment: 'Kettlebell' },
  { id: 'kettlebell-windmill', name: 'Kettlebell Windmill', muscleGroup: 'Abdominaux', equipment: 'Kettlebell' },
  { id: 'knee-hip-raise-on-parallel-bars', name: 'Knee/Hip Raise On Parallel Bars', muscleGroup: 'Abdominaux', equipment: 'Autre' },
  { id: 'kneeling-cable-crunch-with-alternating-oblique-twists', name: 'Kneeling Cable Crunch With Alternating Oblique Twists', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'landmine-180-s', name: 'Landmine 180\'s', muscleGroup: 'Abdominaux', equipment: 'Barre' },
  { id: 'leg-pull-in', name: 'Leg Pull-In', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'oblique-crunches', name: 'Oblique Crunches', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'oblique-crunches-on-the-floor', name: 'Oblique Crunches - On The Floor', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'one-arm-high-pulley-cable-side-bends', name: 'One-Arm High-Pulley Cable Side Bends', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'one-arm-medicine-ball-slam', name: 'One-Arm Medicine Ball Slam', muscleGroup: 'Abdominaux', equipment: 'Medicine ball' },
  { id: 'otis-up', name: 'Otis-Up', muscleGroup: 'Abdominaux', equipment: 'Autre' },
  { id: 'pallof-press', name: 'Pallof Press', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'pallof-press-with-rotation', name: 'Pallof Press With Rotation', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'plank', name: 'Plank', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'plate-twist', name: 'Plate Twist', muscleGroup: 'Abdominaux', equipment: 'Autre' },
  { id: 'press-sit-up', name: 'Press Sit-Up', muscleGroup: 'Abdominaux', equipment: 'Barre' },
  { id: 'reverse-crunch', name: 'Reverse Crunch', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'rope-crunch', name: 'Rope Crunch', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'russian-twist', name: 'Russian Twist', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'seated-barbell-twist', name: 'Seated Barbell Twist', muscleGroup: 'Abdominaux', equipment: 'Barre' },
  { id: 'seated-flat-bench-leg-pull-in', name: 'Seated Flat Bench Leg Pull-In', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'seated-leg-tucks', name: 'Seated Leg Tucks', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'side-bridge', name: 'Side Bridge', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'side-jackknife', name: 'Side Jackknife', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'sit-up', name: 'Sit-Up', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'smith-machine-hip-raise', name: 'Smith Machine Hip Raise', muscleGroup: 'Abdominaux', equipment: 'Machine' },
  { id: 'spell-caster', name: 'Spell Caster', muscleGroup: 'Abdominaux', equipment: 'Haltères' },
  { id: 'spider-crawl', name: 'Spider Crawl', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'standing-cable-lift', name: 'Standing Cable Lift', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'standing-cable-wood-chop', name: 'Standing Cable Wood Chop', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'standing-rope-crunch', name: 'Standing Rope Crunch', muscleGroup: 'Abdominaux', equipment: 'Poulie' },
  { id: 'suspended-fallout', name: 'Suspended Fallout', muscleGroup: 'Abdominaux', equipment: 'Autre' },
  { id: 'suspended-reverse-crunch', name: 'Suspended Reverse Crunch', muscleGroup: 'Abdominaux', equipment: 'Autre' },
  { id: 'tuck-crunch', name: 'Tuck Crunch', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'weighted-ball-side-bend', name: 'Weighted Ball Side Bend', muscleGroup: 'Abdominaux', equipment: 'Swiss ball' },
  { id: 'weighted-crunches', name: 'Weighted Crunches', muscleGroup: 'Abdominaux', equipment: 'Medicine ball' },
  { id: 'weighted-sit-ups-with-bands', name: 'Weighted Sit-Ups - With Bands', muscleGroup: 'Abdominaux', equipment: 'Autre' },
  { id: 'wind-sprints', name: 'Wind Sprints', muscleGroup: 'Abdominaux', equipment: 'Poids du corps' },
  { id: 'monster-walk', name: 'Monster Walk', muscleGroup: 'Abducteurs', equipment: 'Élastique' },
  { id: 'thigh-abductor', name: 'Thigh Abductor', muscleGroup: 'Abducteurs', equipment: 'Machine' },
  { id: 'band-hip-adductions', name: 'Band Hip Adductions', muscleGroup: 'Adducteurs', equipment: 'Élastique' },
  { id: 'thigh-adductor', name: 'Thigh Adductor', muscleGroup: 'Adducteurs', equipment: 'Machine' },
  { id: 'bottoms-up-clean-from-the-hang-position', name: 'Bottoms-Up Clean From The Hang Position', muscleGroup: 'Avant-bras', equipment: 'Kettlebell' },
  { id: 'cable-wrist-curl', name: 'Cable Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Poulie' },
  { id: 'dumbbell-lying-pronation', name: 'Dumbbell Lying Pronation', muscleGroup: 'Avant-bras', equipment: 'Haltères' },
  { id: 'dumbbell-lying-supination', name: 'Dumbbell Lying Supination', muscleGroup: 'Avant-bras', equipment: 'Haltères' },
  { id: 'farmer-s-walk', name: 'Farmer\'s Walk', muscleGroup: 'Avant-bras', equipment: 'Autre' },
  { id: 'finger-curls', name: 'Finger Curls', muscleGroup: 'Avant-bras', equipment: 'Barre' },
  { id: 'palms-down-dumbbell-wrist-curl-over-a-bench', name: 'Palms-Down Dumbbell Wrist Curl Over A Bench', muscleGroup: 'Avant-bras', equipment: 'Haltères' },
  { id: 'palms-down-wrist-curl-over-a-bench', name: 'Palms-Down Wrist Curl Over A Bench', muscleGroup: 'Avant-bras', equipment: 'Barre' },
  { id: 'palms-up-barbell-wrist-curl-over-a-bench', name: 'Palms-Up Barbell Wrist Curl Over A Bench', muscleGroup: 'Avant-bras', equipment: 'Barre' },
  { id: 'palms-up-dumbbell-wrist-curl-over-a-bench', name: 'Palms-Up Dumbbell Wrist Curl Over A Bench', muscleGroup: 'Avant-bras', equipment: 'Haltères' },
  { id: 'plate-pinch', name: 'Plate Pinch', muscleGroup: 'Avant-bras', equipment: 'Autre' },
  { id: 'rickshaw-carry', name: 'Rickshaw Carry', muscleGroup: 'Avant-bras', equipment: 'Autre' },
  { id: 'seated-dumbbell-palms-down-wrist-curl', name: 'Seated Dumbbell Palms-Down Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Haltères' },
  { id: 'seated-dumbbell-palms-up-wrist-curl', name: 'Seated Dumbbell Palms-Up Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Haltères' },
  { id: 'seated-one-arm-dumbbell-palms-down-wrist-curl', name: 'Seated One-Arm Dumbbell Palms-Down Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Haltères' },
  { id: 'seated-one-arm-dumbbell-palms-up-wrist-curl', name: 'Seated One-Arm Dumbbell Palms-Up Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Haltères' },
  { id: 'seated-palm-up-barbell-wrist-curl', name: 'Seated Palm-Up Barbell Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Barre' },
  { id: 'seated-palms-down-barbell-wrist-curl', name: 'Seated Palms-Down Barbell Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Barre' },
  { id: 'seated-two-arm-palms-up-low-pulley-wrist-curl', name: 'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Poulie' },
  { id: 'standing-olympic-plate-hand-squeeze', name: 'Standing Olympic Plate Hand Squeeze', muscleGroup: 'Avant-bras', equipment: 'Autre' },
  { id: 'standing-palms-up-barbell-behind-the-back-wrist-curl', name: 'Standing Palms-Up Barbell Behind The Back Wrist Curl', muscleGroup: 'Avant-bras', equipment: 'Barre' },
  { id: 'wrist-roller', name: 'Wrist Roller', muscleGroup: 'Avant-bras', equipment: 'Autre' },
  { id: 'wrist-rotations-with-straight-bar', name: 'Wrist Rotations with Straight Bar', muscleGroup: 'Avant-bras', equipment: 'Barre' },
  { id: 'atlas-stone-trainer', name: 'Atlas Stone Trainer', muscleGroup: 'Bas du dos', equipment: 'Autre' },
  { id: 'atlas-stones', name: 'Atlas Stones', muscleGroup: 'Bas du dos', equipment: 'Autre' },
  { id: 'axle-deadlift', name: 'Axle Deadlift', muscleGroup: 'Bas du dos', equipment: 'Autre' },
  { id: 'barbell-deadlift', name: 'Barbell Deadlift', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'deadlift-with-bands', name: 'Deadlift with Bands', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'deadlift-with-chains', name: 'Deadlift with Chains', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'deficit-deadlift', name: 'Deficit Deadlift', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'hyperextensions-back-extensions', name: 'Hyperextensions (Back Extensions)', muscleGroup: 'Bas du dos', equipment: 'Autre' },
  { id: 'hyperextensions-with-no-hyperextension-bench', name: 'Hyperextensions With No Hyperextension Bench', muscleGroup: 'Bas du dos', equipment: 'Poids du corps' },
  { id: 'keg-load', name: 'Keg Load', muscleGroup: 'Bas du dos', equipment: 'Autre' },
  { id: 'rack-pull-with-bands', name: 'Rack Pull with Bands', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'rack-pulls', name: 'Rack Pulls', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'reverse-band-deadlift', name: 'Reverse Band Deadlift', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'seated-good-mornings', name: 'Seated Good Mornings', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'stiff-leg-barbell-good-morning', name: 'Stiff Leg Barbell Good Morning', muscleGroup: 'Bas du dos', equipment: 'Barre' },
  { id: 'weighted-ball-hyperextension', name: 'Weighted Ball Hyperextension', muscleGroup: 'Bas du dos', equipment: 'Swiss ball' },
  { id: 'alternate-hammer-curl', name: 'Alternate Hammer Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'alternate-incline-dumbbell-curl', name: 'Alternate Incline Dumbbell Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'barbell-curl', name: 'Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'barbell-curls-lying-against-an-incline', name: 'Barbell Curls Lying Against An Incline', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'cable-hammer-curls-rope-attachment', name: 'Cable Hammer Curls - Rope Attachment', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'cable-preacher-curl', name: 'Cable Preacher Curl', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'close-grip-ez-bar-curl', name: 'Close-Grip EZ Bar Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'close-grip-ez-bar-curl-with-band', name: 'Close-Grip EZ-Bar Curl with Band', muscleGroup: 'Biceps', equipment: 'Barre EZ' },
  { id: 'close-grip-standing-barbell-curl', name: 'Close-Grip Standing Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'concentration-curls', name: 'Concentration Curls', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'cross-body-hammer-curl', name: 'Cross Body Hammer Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'drag-curl', name: 'Drag Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'dumbbell-alternate-bicep-curl', name: 'Dumbbell Alternate Bicep Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'dumbbell-bicep-curl', name: 'Dumbbell Bicep Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'dumbbell-prone-incline-curl', name: 'Dumbbell Prone Incline Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'ez-bar-curl', name: 'EZ-Bar Curl', muscleGroup: 'Biceps', equipment: 'Barre EZ' },
  { id: 'flexor-incline-dumbbell-curls', name: 'Flexor Incline Dumbbell Curls', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'hammer-curls', name: 'Hammer Curls', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'high-cable-curls', name: 'High Cable Curls', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'incline-dumbbell-curl', name: 'Incline Dumbbell Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'incline-hammer-curls', name: 'Incline Hammer Curls', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'incline-inner-biceps-curl', name: 'Incline Inner Biceps Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'lying-cable-curl', name: 'Lying Cable Curl', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'lying-close-grip-bar-curl-on-high-pulley', name: 'Lying Close-Grip Bar Curl On High Pulley', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'lying-high-bench-barbell-curl', name: 'Lying High Bench Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'lying-supine-dumbbell-curl', name: 'Lying Supine Dumbbell Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'machine-bicep-curl', name: 'Machine Bicep Curl', muscleGroup: 'Biceps', equipment: 'Machine' },
  { id: 'machine-preacher-curls', name: 'Machine Preacher Curls', muscleGroup: 'Biceps', equipment: 'Machine' },
  { id: 'one-arm-dumbbell-preacher-curl', name: 'One Arm Dumbbell Preacher Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'overhead-cable-curl', name: 'Overhead Cable Curl', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'preacher-curl', name: 'Preacher Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'preacher-hammer-dumbbell-curl', name: 'Preacher Hammer Dumbbell Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'reverse-barbell-curl', name: 'Reverse Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'reverse-barbell-preacher-curls', name: 'Reverse Barbell Preacher Curls', muscleGroup: 'Biceps', equipment: 'Barre EZ' },
  { id: 'reverse-cable-curl', name: 'Reverse Cable Curl', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'reverse-plate-curls', name: 'Reverse Plate Curls', muscleGroup: 'Biceps', equipment: 'Autre' },
  { id: 'seated-close-grip-concentration-barbell-curl', name: 'Seated Close-Grip Concentration Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'seated-dumbbell-curl', name: 'Seated Dumbbell Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'seated-dumbbell-inner-biceps-curl', name: 'Seated Dumbbell Inner Biceps Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'spider-curl', name: 'Spider Curl', muscleGroup: 'Biceps', equipment: 'Barre EZ' },
  { id: 'standing-biceps-cable-curl', name: 'Standing Biceps Cable Curl', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'standing-concentration-curl', name: 'Standing Concentration Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'standing-dumbbell-reverse-curl', name: 'Standing Dumbbell Reverse Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'standing-inner-biceps-curl', name: 'Standing Inner-Biceps Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'standing-one-arm-cable-curl', name: 'Standing One-Arm Cable Curl', muscleGroup: 'Biceps', equipment: 'Poulie' },
  { id: 'standing-one-arm-dumbbell-curl-over-incline-bench', name: 'Standing One-Arm Dumbbell Curl Over Incline Bench', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'two-arm-dumbbell-preacher-curl', name: 'Two-Arm Dumbbell Preacher Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'wide-grip-standing-barbell-curl', name: 'Wide-Grip Standing Barbell Curl', muscleGroup: 'Biceps', equipment: 'Barre' },
  { id: 'zottman-curl', name: 'Zottman Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'zottman-preacher-curl', name: 'Zottman Preacher Curl', muscleGroup: 'Biceps', equipment: 'Haltères' },
  { id: 'band-assisted-pull-up', name: 'Band Assisted Pull-Up', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'bent-arm-barbell-pullover', name: 'Bent-Arm Barbell Pullover', muscleGroup: 'Dos', equipment: 'Barre' },
  { id: 'cable-incline-pushdown', name: 'Cable Incline Pushdown', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'chin-up', name: 'Chin-Up', muscleGroup: 'Dos', equipment: 'Poids du corps' },
  { id: 'close-grip-front-lat-pulldown', name: 'Close-Grip Front Lat Pulldown', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'elevated-cable-rows', name: 'Elevated Cable Rows', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'full-range-of-motion-lat-pulldown', name: 'Full Range-Of-Motion Lat Pulldown', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'gironda-sternum-chins', name: 'Gironda Sternum Chins', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'kipping-muscle-up', name: 'Kipping Muscle Up', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'kneeling-high-pulley-row', name: 'Kneeling High Pulley Row', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'kneeling-single-arm-high-pulley-row', name: 'Kneeling Single-Arm High Pulley Row', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'leverage-iso-row', name: 'Leverage Iso Row', muscleGroup: 'Dos', equipment: 'Machine' },
  { id: 'london-bridges', name: 'London Bridges', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'muscle-up', name: 'Muscle Up', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'one-arm-lat-pulldown', name: 'One Arm Lat Pulldown', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'pullups', name: 'Pullups', muscleGroup: 'Dos', equipment: 'Poids du corps' },
  { id: 'rocky-pull-ups-pulldowns', name: 'Rocky Pull-Ups/Pulldowns', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'rope-climb', name: 'Rope Climb', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'rope-straight-arm-pulldown', name: 'Rope Straight-Arm Pulldown', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'shotgun-row', name: 'Shotgun Row', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'side-to-side-chins', name: 'Side To Side Chins', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'straight-arm-pulldown', name: 'Straight-Arm Pulldown', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'underhand-cable-pulldowns', name: 'Underhand Cable Pulldowns', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'v-bar-pulldown', name: 'V-Bar Pulldown', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'v-bar-pullup', name: 'V-Bar Pullup', muscleGroup: 'Dos', equipment: 'Poids du corps' },
  { id: 'weighted-pull-ups', name: 'Weighted Pull Ups', muscleGroup: 'Dos', equipment: 'Autre' },
  { id: 'wide-grip-lat-pulldown', name: 'Wide-Grip Lat Pulldown', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'wide-grip-pulldown-behind-the-neck', name: 'Wide-Grip Pulldown Behind The Neck', muscleGroup: 'Dos', equipment: 'Poulie' },
  { id: 'wide-grip-rear-pull-up', name: 'Wide-Grip Rear Pull-Up', muscleGroup: 'Dos', equipment: 'Poids du corps' },
  { id: 'barbell-glute-bridge', name: 'Barbell Glute Bridge', muscleGroup: 'Fessiers', equipment: 'Barre' },
  { id: 'barbell-hip-thrust', name: 'Barbell Hip Thrust', muscleGroup: 'Fessiers', equipment: 'Barre' },
  { id: 'butt-lift-bridge', name: 'Butt Lift (Bridge)', muscleGroup: 'Fessiers', equipment: 'Poids du corps' },
  { id: 'downward-facing-balance', name: 'Downward Facing Balance', muscleGroup: 'Fessiers', equipment: 'Swiss ball' },
  { id: 'flutter-kicks', name: 'Flutter Kicks', muscleGroup: 'Fessiers', equipment: 'Poids du corps' },
  { id: 'glute-kickback', name: 'Glute Kickback', muscleGroup: 'Fessiers', equipment: 'Poids du corps' },
  { id: 'hip-extension-with-bands', name: 'Hip Extension with Bands', muscleGroup: 'Fessiers', equipment: 'Élastique' },
  { id: 'hip-lift-with-band', name: 'Hip Lift with Band', muscleGroup: 'Fessiers', equipment: 'Élastique' },
  { id: 'kneeling-jump-squat', name: 'Kneeling Jump Squat', muscleGroup: 'Fessiers', equipment: 'Barre' },
  { id: 'kneeling-squat', name: 'Kneeling Squat', muscleGroup: 'Fessiers', equipment: 'Barre' },
  { id: 'leg-lift', name: 'Leg Lift', muscleGroup: 'Fessiers', equipment: 'Poids du corps' },
  { id: 'one-legged-cable-kickback', name: 'One-Legged Cable Kickback', muscleGroup: 'Fessiers', equipment: 'Poulie' },
  { id: 'physioball-hip-bridge', name: 'Physioball Hip Bridge', muscleGroup: 'Fessiers', equipment: 'Swiss ball' },
  { id: 'pull-through', name: 'Pull Through', muscleGroup: 'Fessiers', equipment: 'Poulie' },
  { id: 'single-leg-glute-bridge', name: 'Single Leg Glute Bridge', muscleGroup: 'Fessiers', equipment: 'Poids du corps' },
  { id: 'step-up-with-knee-raise', name: 'Step-up with Knee Raise', muscleGroup: 'Fessiers', equipment: 'Poids du corps' },
  { id: 'alternating-hang-clean', name: 'Alternating Hang Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'ball-leg-curl', name: 'Ball Leg Curl', muscleGroup: 'Ischio-jambiers', equipment: 'Swiss ball' },
  { id: 'band-good-morning', name: 'Band Good Morning', muscleGroup: 'Ischio-jambiers', equipment: 'Élastique' },
  { id: 'band-good-morning-pull-through', name: 'Band Good Morning (Pull Through)', muscleGroup: 'Ischio-jambiers', equipment: 'Élastique' },
  { id: 'clean', name: 'Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'clean-deadlift', name: 'Clean Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'double-kettlebell-alternating-hang-clean', name: 'Double Kettlebell Alternating Hang Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'dumbbell-clean', name: 'Dumbbell Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Haltères' },
  { id: 'floor-glute-ham-raise', name: 'Floor Glute-Ham Raise', muscleGroup: 'Ischio-jambiers', equipment: 'Autre' },
  { id: 'glute-ham-raise', name: 'Glute Ham Raise', muscleGroup: 'Ischio-jambiers', equipment: 'Machine' },
  { id: 'good-morning', name: 'Good Morning', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'good-morning-off-pins', name: 'Good Morning off Pins', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'hang-snatch', name: 'Hang Snatch', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'hang-snatch-below-knees', name: 'Hang Snatch - Below Knees', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'hanging-bar-good-morning', name: 'Hanging Bar Good Morning', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'kettlebell-dead-clean', name: 'Kettlebell Dead Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'kettlebell-hang-clean', name: 'Kettlebell Hang Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'kettlebell-one-legged-deadlift', name: 'Kettlebell One-Legged Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'lunge-pass-through', name: 'Lunge Pass Through', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'lying-leg-curls', name: 'Lying Leg Curls', muscleGroup: 'Ischio-jambiers', equipment: 'Machine' },
  { id: 'muscle-snatch', name: 'Muscle Snatch', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'natural-glute-ham-raise', name: 'Natural Glute Ham Raise', muscleGroup: 'Ischio-jambiers', equipment: 'Poids du corps' },
  { id: 'one-arm-kettlebell-clean', name: 'One-Arm Kettlebell Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'one-arm-kettlebell-swings', name: 'One-Arm Kettlebell Swings', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'one-arm-open-palm-kettlebell-clean', name: 'One-Arm Open Palm Kettlebell Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'open-palm-kettlebell-clean', name: 'Open Palm Kettlebell Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Kettlebell' },
  { id: 'platform-hamstring-slides', name: 'Platform Hamstring Slides', muscleGroup: 'Ischio-jambiers', equipment: 'Autre' },
  { id: 'power-clean', name: 'Power Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'power-clean-from-blocks', name: 'Power Clean from Blocks', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'power-snatch', name: 'Power Snatch', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'power-stairs', name: 'Power Stairs', muscleGroup: 'Ischio-jambiers', equipment: 'Autre' },
  { id: 'prone-manual-hamstring', name: 'Prone Manual Hamstring', muscleGroup: 'Ischio-jambiers', equipment: 'Autre' },
  { id: 'reverse-band-sumo-deadlift', name: 'Reverse Band Sumo Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'reverse-hyperextension', name: 'Reverse Hyperextension', muscleGroup: 'Ischio-jambiers', equipment: 'Machine' },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'romanian-deadlift-from-deficit', name: 'Romanian Deadlift from Deficit', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'seated-band-hamstring-curl', name: 'Seated Band Hamstring Curl', muscleGroup: 'Ischio-jambiers', equipment: 'Autre' },
  { id: 'seated-leg-curl', name: 'Seated Leg Curl', muscleGroup: 'Ischio-jambiers', equipment: 'Machine' },
  { id: 'smith-machine-hang-power-clean', name: 'Smith Machine Hang Power Clean', muscleGroup: 'Ischio-jambiers', equipment: 'Machine' },
  { id: 'smith-machine-stiff-legged-deadlift', name: 'Smith Machine Stiff-Legged Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Machine' },
  { id: 'snatch-deadlift', name: 'Snatch Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'snatch-pull', name: 'Snatch Pull', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'split-snatch', name: 'Split Snatch', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'standing-leg-curl', name: 'Standing Leg Curl', muscleGroup: 'Ischio-jambiers', equipment: 'Machine' },
  { id: 'stiff-legged-barbell-deadlift', name: 'Stiff-Legged Barbell Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'stiff-legged-dumbbell-deadlift', name: 'Stiff-Legged Dumbbell Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Haltères' },
  { id: 'sumo-deadlift', name: 'Sumo Deadlift', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'sumo-deadlift-with-bands', name: 'Sumo Deadlift with Bands', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'sumo-deadlift-with-chains', name: 'Sumo Deadlift with Chains', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'wide-stance-stiff-legs', name: 'Wide Stance Stiff Legs', muscleGroup: 'Ischio-jambiers', equipment: 'Barre' },
  { id: 'alternating-kettlebell-row', name: 'Alternating Kettlebell Row', muscleGroup: 'Milieu du dos', equipment: 'Kettlebell' },
  { id: 'alternating-renegade-row', name: 'Alternating Renegade Row', muscleGroup: 'Milieu du dos', equipment: 'Kettlebell' },
  { id: 'bent-over-barbell-row', name: 'Bent Over Barbell Row', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'bent-over-one-arm-long-bar-row', name: 'Bent Over One-Arm Long Bar Row', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'bent-over-two-arm-long-bar-row', name: 'Bent Over Two-Arm Long Bar Row', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'bent-over-two-dumbbell-row', name: 'Bent Over Two-Dumbbell Row', muscleGroup: 'Milieu du dos', equipment: 'Haltères' },
  { id: 'bent-over-two-dumbbell-row-with-palms-in', name: 'Bent Over Two-Dumbbell Row With Palms In', muscleGroup: 'Milieu du dos', equipment: 'Haltères' },
  { id: 'bodyweight-mid-row', name: 'Bodyweight Mid Row', muscleGroup: 'Milieu du dos', equipment: 'Autre' },
  { id: 'dumbbell-incline-row', name: 'Dumbbell Incline Row', muscleGroup: 'Milieu du dos', equipment: 'Haltères' },
  { id: 'incline-bench-pull', name: 'Incline Bench Pull', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'inverted-row', name: 'Inverted Row', muscleGroup: 'Milieu du dos', equipment: 'Autre' },
  { id: 'inverted-row-with-straps', name: 'Inverted Row with Straps', muscleGroup: 'Milieu du dos', equipment: 'Autre' },
  { id: 'leverage-high-row', name: 'Leverage High Row', muscleGroup: 'Milieu du dos', equipment: 'Machine' },
  { id: 'lying-cambered-barbell-row', name: 'Lying Cambered Barbell Row', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'lying-t-bar-row', name: 'Lying T-Bar Row', muscleGroup: 'Milieu du dos', equipment: 'Machine' },
  { id: 'middle-back-shrug', name: 'Middle Back Shrug', muscleGroup: 'Milieu du dos', equipment: 'Haltères' },
  { id: 'mixed-grip-chin', name: 'Mixed Grip Chin', muscleGroup: 'Milieu du dos', equipment: 'Autre' },
  { id: 'one-arm-chin-up', name: 'One Arm Chin-Up', muscleGroup: 'Milieu du dos', equipment: 'Autre' },
  { id: 'one-arm-dumbbell-row', name: 'One-Arm Dumbbell Row', muscleGroup: 'Milieu du dos', equipment: 'Haltères' },
  { id: 'one-arm-kettlebell-row', name: 'One-Arm Kettlebell Row', muscleGroup: 'Milieu du dos', equipment: 'Kettlebell' },
  { id: 'one-arm-long-bar-row', name: 'One-Arm Long Bar Row', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'reverse-grip-bent-over-rows', name: 'Reverse Grip Bent-Over Rows', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'seated-cable-rows', name: 'Seated Cable Rows', muscleGroup: 'Milieu du dos', equipment: 'Poulie' },
  { id: 'seated-one-arm-cable-pulley-rows', name: 'Seated One-arm Cable Pulley Rows', muscleGroup: 'Milieu du dos', equipment: 'Poulie' },
  { id: 'sled-row', name: 'Sled Row', muscleGroup: 'Milieu du dos', equipment: 'Autre' },
  { id: 'smith-machine-bent-over-row', name: 'Smith Machine Bent Over Row', muscleGroup: 'Milieu du dos', equipment: 'Machine' },
  { id: 'straight-bar-bench-mid-rows', name: 'Straight Bar Bench Mid Rows', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'suspended-row', name: 'Suspended Row', muscleGroup: 'Milieu du dos', equipment: 'Autre' },
  { id: 't-bar-row-with-handle', name: 'T-Bar Row with Handle', muscleGroup: 'Milieu du dos', equipment: 'Barre' },
  { id: 'two-arm-kettlebell-row', name: 'Two-Arm Kettlebell Row', muscleGroup: 'Milieu du dos', equipment: 'Kettlebell' },
  { id: 'balance-board', name: 'Balance Board', muscleGroup: 'Mollets', equipment: 'Autre' },
  { id: 'barbell-seated-calf-raise', name: 'Barbell Seated Calf Raise', muscleGroup: 'Mollets', equipment: 'Barre' },
  { id: 'calf-press', name: 'Calf Press', muscleGroup: 'Mollets', equipment: 'Machine' },
  { id: 'calf-press-on-the-leg-press-machine', name: 'Calf Press On The Leg Press Machine', muscleGroup: 'Mollets', equipment: 'Machine' },
  { id: 'calf-raise-on-a-dumbbell', name: 'Calf Raise On A Dumbbell', muscleGroup: 'Mollets', equipment: 'Haltères' },
  { id: 'calf-raises-with-bands', name: 'Calf Raises - With Bands', muscleGroup: 'Mollets', equipment: 'Élastique' },
  { id: 'donkey-calf-raises', name: 'Donkey Calf Raises', muscleGroup: 'Mollets', equipment: 'Autre' },
  { id: 'dumbbell-seated-one-leg-calf-raise', name: 'Dumbbell Seated One-Leg Calf Raise', muscleGroup: 'Mollets', equipment: 'Haltères' },
  { id: 'rocking-standing-calf-raise', name: 'Rocking Standing Calf Raise', muscleGroup: 'Mollets', equipment: 'Barre' },
  { id: 'seated-calf-raise', name: 'Seated Calf Raise', muscleGroup: 'Mollets', equipment: 'Machine' },
  { id: 'smith-machine-calf-raise', name: 'Smith Machine Calf Raise', muscleGroup: 'Mollets', equipment: 'Machine' },
  { id: 'smith-machine-reverse-calf-raises', name: 'Smith Machine Reverse Calf Raises', muscleGroup: 'Mollets', equipment: 'Machine' },
  { id: 'standing-barbell-calf-raise', name: 'Standing Barbell Calf Raise', muscleGroup: 'Mollets', equipment: 'Barre' },
  { id: 'standing-calf-raises', name: 'Standing Calf Raises', muscleGroup: 'Mollets', equipment: 'Machine' },
  { id: 'standing-dumbbell-calf-raise', name: 'Standing Dumbbell Calf Raise', muscleGroup: 'Mollets', equipment: 'Haltères' },
  { id: 'isometric-neck-exercise-front-and-back', name: 'Isometric Neck Exercise - Front And Back', muscleGroup: 'Nuque', equipment: 'Poids du corps' },
  { id: 'isometric-neck-exercise-sides', name: 'Isometric Neck Exercise - Sides', muscleGroup: 'Nuque', equipment: 'Poids du corps' },
  { id: 'lying-face-down-plate-neck-resistance', name: 'Lying Face Down Plate Neck Resistance', muscleGroup: 'Nuque', equipment: 'Autre' },
  { id: 'lying-face-up-plate-neck-resistance', name: 'Lying Face Up Plate Neck Resistance', muscleGroup: 'Nuque', equipment: 'Autre' },
  { id: 'seated-head-harness-neck-resistance', name: 'Seated Head Harness Neck Resistance', muscleGroup: 'Nuque', equipment: 'Autre' },
  { id: 'alternating-floor-press', name: 'Alternating Floor Press', muscleGroup: 'Pectoraux', equipment: 'Kettlebell' },
  { id: 'around-the-worlds', name: 'Around The Worlds', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'barbell-bench-press-medium-grip', name: 'Barbell Bench Press - Medium Grip', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'barbell-guillotine-bench-press', name: 'Barbell Guillotine Bench Press', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'barbell-incline-bench-press-medium-grip', name: 'Barbell Incline Bench Press - Medium Grip', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'bench-press-with-bands', name: 'Bench Press - With Bands', muscleGroup: 'Pectoraux', equipment: 'Élastique' },
  { id: 'bent-arm-dumbbell-pullover', name: 'Bent-Arm Dumbbell Pullover', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'bodyweight-flyes', name: 'Bodyweight Flyes', muscleGroup: 'Pectoraux', equipment: 'Barre EZ' },
  { id: 'butterfly', name: 'Butterfly', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'cable-chest-press', name: 'Cable Chest Press', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'cable-crossover', name: 'Cable Crossover', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'cable-iron-cross', name: 'Cable Iron Cross', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'chain-press', name: 'Chain Press', muscleGroup: 'Pectoraux', equipment: 'Autre' },
  { id: 'clock-push-up', name: 'Clock Push-Up', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'cross-over-with-bands', name: 'Cross Over - With Bands', muscleGroup: 'Pectoraux', equipment: 'Élastique' },
  { id: 'decline-barbell-bench-press', name: 'Decline Barbell Bench Press', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'decline-dumbbell-bench-press', name: 'Decline Dumbbell Bench Press', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'decline-dumbbell-flyes', name: 'Decline Dumbbell Flyes', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'decline-push-up', name: 'Decline Push-Up', muscleGroup: 'Pectoraux', equipment: 'Autre' },
  { id: 'decline-smith-press', name: 'Decline Smith Press', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'dips-chest-version', name: 'Dips - Chest Version', muscleGroup: 'Pectoraux', equipment: 'Autre' },
  { id: 'dumbbell-bench-press', name: 'Dumbbell Bench Press', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'dumbbell-bench-press-with-neutral-grip', name: 'Dumbbell Bench Press with Neutral Grip', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'dumbbell-flyes', name: 'Dumbbell Flyes', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'extended-range-one-arm-kettlebell-floor-press', name: 'Extended Range One-Arm Kettlebell Floor Press', muscleGroup: 'Pectoraux', equipment: 'Kettlebell' },
  { id: 'flat-bench-cable-flyes', name: 'Flat Bench Cable Flyes', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'forward-drag-with-press', name: 'Forward Drag with Press', muscleGroup: 'Pectoraux', equipment: 'Autre' },
  { id: 'front-raise-and-pullover', name: 'Front Raise And Pullover', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'hammer-grip-incline-db-bench-press', name: 'Hammer Grip Incline DB Bench Press', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'incline-cable-chest-press', name: 'Incline Cable Chest Press', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'incline-cable-flye', name: 'Incline Cable Flye', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'incline-dumbbell-bench-with-palms-facing-in', name: 'Incline Dumbbell Bench With Palms Facing In', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'incline-dumbbell-flyes', name: 'Incline Dumbbell Flyes', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'incline-dumbbell-flyes-with-a-twist', name: 'Incline Dumbbell Flyes - With A Twist', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'incline-dumbbell-press', name: 'Incline Dumbbell Press', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'incline-push-up', name: 'Incline Push-Up', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'incline-push-up-medium', name: 'Incline Push-Up Medium', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'incline-push-up-reverse-grip', name: 'Incline Push-Up Reverse Grip', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'incline-push-up-wide', name: 'Incline Push-Up Wide', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'isometric-wipers', name: 'Isometric Wipers', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'leg-over-floor-press', name: 'Leg-Over Floor Press', muscleGroup: 'Pectoraux', equipment: 'Kettlebell' },
  { id: 'leverage-chest-press', name: 'Leverage Chest Press', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'leverage-decline-chest-press', name: 'Leverage Decline Chest Press', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'leverage-incline-chest-press', name: 'Leverage Incline Chest Press', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'low-cable-crossover', name: 'Low Cable Crossover', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'machine-bench-press', name: 'Machine Bench Press', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'neck-press', name: 'Neck Press', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'one-arm-dumbbell-bench-press', name: 'One Arm Dumbbell Bench Press', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'one-arm-flat-bench-dumbbell-flye', name: 'One-Arm Flat Bench Dumbbell Flye', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'one-arm-kettlebell-floor-press', name: 'One-Arm Kettlebell Floor Press', muscleGroup: 'Pectoraux', equipment: 'Kettlebell' },
  { id: 'plyo-kettlebell-pushups', name: 'Plyo Kettlebell Pushups', muscleGroup: 'Pectoraux', equipment: 'Kettlebell' },
  { id: 'push-up-to-side-plank', name: 'Push Up to Side Plank', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'push-up-wide', name: 'Push-Up Wide', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'push-ups-with-feet-elevated', name: 'Push-Ups With Feet Elevated', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'push-ups-with-feet-on-an-exercise-ball', name: 'Push-Ups With Feet On An Exercise Ball', muscleGroup: 'Pectoraux', equipment: 'Swiss ball' },
  { id: 'pushups', name: 'Pushups', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'pushups-close-and-wide-hand-positions', name: 'Pushups (Close and Wide Hand Positions)', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'single-arm-cable-crossover', name: 'Single-Arm Cable Crossover', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'single-arm-push-up', name: 'Single-Arm Push-Up', muscleGroup: 'Pectoraux', equipment: 'Poids du corps' },
  { id: 'smith-machine-bench-press', name: 'Smith Machine Bench Press', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'smith-machine-decline-press', name: 'Smith Machine Decline Press', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'smith-machine-incline-bench-press', name: 'Smith Machine Incline Bench Press', muscleGroup: 'Pectoraux', equipment: 'Machine' },
  { id: 'standing-cable-chest-press', name: 'Standing Cable Chest Press', muscleGroup: 'Pectoraux', equipment: 'Poulie' },
  { id: 'straight-arm-dumbbell-pullover', name: 'Straight-Arm Dumbbell Pullover', muscleGroup: 'Pectoraux', equipment: 'Haltères' },
  { id: 'suspended-push-up', name: 'Suspended Push-Up', muscleGroup: 'Pectoraux', equipment: 'Autre' },
  { id: 'svend-press', name: 'Svend Press', muscleGroup: 'Pectoraux', equipment: 'Autre' },
  { id: 'wide-grip-barbell-bench-press', name: 'Wide-Grip Barbell Bench Press', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'wide-grip-decline-barbell-bench-press', name: 'Wide-Grip Decline Barbell Bench Press', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'wide-grip-decline-barbell-pullover', name: 'Wide-Grip Decline Barbell Pullover', muscleGroup: 'Pectoraux', equipment: 'Barre' },
  { id: 'backward-drag', name: 'Backward Drag', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'barbell-full-squat', name: 'Barbell Full Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'barbell-hack-squat', name: 'Barbell Hack Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'barbell-lunge', name: 'Barbell Lunge', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'barbell-side-split-squat', name: 'Barbell Side Split Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'barbell-squat', name: 'Barbell Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'barbell-squat-to-a-bench', name: 'Barbell Squat To A Bench', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'barbell-step-ups', name: 'Barbell Step Ups', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'barbell-walking-lunge', name: 'Barbell Walking Lunge', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'bear-crawl-sled-drags', name: 'Bear Crawl Sled Drags', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'bodyweight-squat', name: 'Bodyweight Squat', muscleGroup: 'Quadriceps', equipment: 'Poids du corps' },
  { id: 'bodyweight-walking-lunge', name: 'Bodyweight Walking Lunge', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'box-squat', name: 'Box Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'box-squat-with-bands', name: 'Box Squat with Bands', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'box-squat-with-chains', name: 'Box Squat with Chains', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'cable-deadlifts', name: 'Cable Deadlifts', muscleGroup: 'Quadriceps', equipment: 'Poulie' },
  { id: 'cable-hip-adduction', name: 'Cable Hip Adduction', muscleGroup: 'Quadriceps', equipment: 'Poulie' },
  { id: 'car-deadlift', name: 'Car Deadlift', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'chair-squat', name: 'Chair Squat', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'clean-pull', name: 'Clean Pull', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'clean-from-blocks', name: 'Clean from Blocks', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'conan-s-wheel', name: 'Conan\'s Wheel', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'dumbbell-lunges', name: 'Dumbbell Lunges', muscleGroup: 'Quadriceps', equipment: 'Haltères' },
  { id: 'dumbbell-rear-lunge', name: 'Dumbbell Rear Lunge', muscleGroup: 'Quadriceps', equipment: 'Haltères' },
  { id: 'dumbbell-squat', name: 'Dumbbell Squat', muscleGroup: 'Quadriceps', equipment: 'Haltères' },
  { id: 'dumbbell-squat-to-a-bench', name: 'Dumbbell Squat To A Bench', muscleGroup: 'Quadriceps', equipment: 'Haltères' },
  { id: 'dumbbell-step-ups', name: 'Dumbbell Step Ups', muscleGroup: 'Quadriceps', equipment: 'Haltères' },
  { id: 'elevated-back-lunge', name: 'Elevated Back Lunge', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'frankenstein-squat', name: 'Frankenstein Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'freehand-jump-squat', name: 'Freehand Jump Squat', muscleGroup: 'Quadriceps', equipment: 'Poids du corps' },
  { id: 'front-barbell-squat', name: 'Front Barbell Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'front-barbell-squat-to-a-bench', name: 'Front Barbell Squat To A Bench', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'front-squat-clean-grip', name: 'Front Squat (Clean Grip)', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'front-squats-with-two-kettlebells', name: 'Front Squats With Two Kettlebells', muscleGroup: 'Quadriceps', equipment: 'Kettlebell' },
  { id: 'goblet-squat', name: 'Goblet Squat', muscleGroup: 'Quadriceps', equipment: 'Kettlebell' },
  { id: 'hack-squat', name: 'Hack Squat', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'hang-clean', name: 'Hang Clean', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'hang-clean-below-the-knees', name: 'Hang Clean - Below the Knees', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'heaving-snatch-balance', name: 'Heaving Snatch Balance', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'hip-flexion-with-band', name: 'Hip Flexion with Band', muscleGroup: 'Quadriceps', equipment: 'Élastique' },
  { id: 'jefferson-squats', name: 'Jefferson Squats', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'jerk-dip-squat', name: 'Jerk Dip Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'kettlebell-pistol-squat', name: 'Kettlebell Pistol Squat', muscleGroup: 'Quadriceps', equipment: 'Kettlebell' },
  { id: 'leg-extensions', name: 'Leg Extensions', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'leg-press', name: 'Leg Press', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'leverage-deadlift', name: 'Leverage Deadlift', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'lunge-sprint', name: 'Lunge Sprint', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'lying-machine-squat', name: 'Lying Machine Squat', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'narrow-stance-hack-squats', name: 'Narrow Stance Hack Squats', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'narrow-stance-leg-press', name: 'Narrow Stance Leg Press', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'narrow-stance-squats', name: 'Narrow Stance Squats', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'olympic-squat', name: 'Olympic Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'one-leg-barbell-squat', name: 'One Leg Barbell Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'one-arm-overhead-kettlebell-squats', name: 'One-Arm Overhead Kettlebell Squats', muscleGroup: 'Quadriceps', equipment: 'Kettlebell' },
  { id: 'one-arm-side-deadlift', name: 'One-Arm Side Deadlift', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'overhead-squat', name: 'Overhead Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'plie-dumbbell-squat', name: 'Plie Dumbbell Squat', muscleGroup: 'Quadriceps', equipment: 'Haltères' },
  { id: 'power-jerk', name: 'Power Jerk', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'power-snatch-from-blocks', name: 'Power Snatch from Blocks', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'reverse-band-box-squat', name: 'Reverse Band Box Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'reverse-band-power-squat', name: 'Reverse Band Power Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'rickshaw-deadlift', name: 'Rickshaw Deadlift', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'sandbag-load', name: 'Sandbag Load', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'single-leg-high-box-squat', name: 'Single-Leg High Box Squat', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'single-leg-leg-extension', name: 'Single-Leg Leg Extension', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'sled-drag-harness', name: 'Sled Drag - Harness', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'sled-push', name: 'Sled Push', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'smith-machine-leg-press', name: 'Smith Machine Leg Press', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'smith-machine-pistol-squat', name: 'Smith Machine Pistol Squat', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'smith-machine-squat', name: 'Smith Machine Squat', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'smith-single-leg-split-squat', name: 'Smith Single-Leg Split Squat', muscleGroup: 'Quadriceps', equipment: 'Machine' },
  { id: 'snatch', name: 'Snatch', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'snatch-balance', name: 'Snatch Balance', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'snatch-from-blocks', name: 'Snatch from Blocks', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'speed-box-squat', name: 'Speed Box Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'speed-squats', name: 'Speed Squats', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'split-clean', name: 'Split Clean', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'split-jerk', name: 'Split Jerk', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'split-squat-with-dumbbells', name: 'Split Squat with Dumbbells', muscleGroup: 'Quadriceps', equipment: 'Haltères' },
  { id: 'squat-jerk', name: 'Squat Jerk', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'squat-with-bands', name: 'Squat with Bands', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'squat-with-chains', name: 'Squat with Chains', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'squat-with-plate-movers', name: 'Squat with Plate Movers', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'squats-with-bands', name: 'Squats - With Bands', muscleGroup: 'Quadriceps', equipment: 'Élastique' },
  { id: 'suspended-split-squat', name: 'Suspended Split Squat', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'tire-flip', name: 'Tire Flip', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'trap-bar-deadlift', name: 'Trap Bar Deadlift', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'weighted-jump-squat', name: 'Weighted Jump Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'weighted-sissy-squat', name: 'Weighted Sissy Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'weighted-squat', name: 'Weighted Squat', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'wide-stance-barbell-squat', name: 'Wide Stance Barbell Squat', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'yoke-walk', name: 'Yoke Walk', muscleGroup: 'Quadriceps', equipment: 'Autre' },
  { id: 'zercher-squats', name: 'Zercher Squats', muscleGroup: 'Quadriceps', equipment: 'Barre' },
  { id: 'barbell-shrug', name: 'Barbell Shrug', muscleGroup: 'Trapèzes', equipment: 'Barre' },
  { id: 'barbell-shrug-behind-the-back', name: 'Barbell Shrug Behind The Back', muscleGroup: 'Trapèzes', equipment: 'Barre' },
  { id: 'cable-shrugs', name: 'Cable Shrugs', muscleGroup: 'Trapèzes', equipment: 'Poulie' },
  { id: 'calf-machine-shoulder-shrug', name: 'Calf-Machine Shoulder Shrug', muscleGroup: 'Trapèzes', equipment: 'Machine' },
  { id: 'clean-shrug', name: 'Clean Shrug', muscleGroup: 'Trapèzes', equipment: 'Barre' },
  { id: 'dumbbell-shrug', name: 'Dumbbell Shrug', muscleGroup: 'Trapèzes', equipment: 'Haltères' },
  { id: 'kettlebell-sumo-high-pull', name: 'Kettlebell Sumo High Pull', muscleGroup: 'Trapèzes', equipment: 'Kettlebell' },
  { id: 'leverage-shrug', name: 'Leverage Shrug', muscleGroup: 'Trapèzes', equipment: 'Machine' },
  { id: 'scapular-pull-up', name: 'Scapular Pull-Up', muscleGroup: 'Trapèzes', equipment: 'Autre' },
  { id: 'smith-machine-behind-the-back-shrug', name: 'Smith Machine Behind the Back Shrug', muscleGroup: 'Trapèzes', equipment: 'Machine' },
  { id: 'smith-machine-upright-row', name: 'Smith Machine Upright Row', muscleGroup: 'Trapèzes', equipment: 'Machine' },
  { id: 'snatch-shrug', name: 'Snatch Shrug', muscleGroup: 'Trapèzes', equipment: 'Barre' },
  { id: 'standing-dumbbell-upright-row', name: 'Standing Dumbbell Upright Row', muscleGroup: 'Trapèzes', equipment: 'Haltères' },
  { id: 'upright-cable-row', name: 'Upright Cable Row', muscleGroup: 'Trapèzes', equipment: 'Poulie' },
  { id: 'upright-row-with-bands', name: 'Upright Row - With Bands', muscleGroup: 'Trapèzes', equipment: 'Élastique' },
  { id: 'band-skull-crusher', name: 'Band Skull Crusher', muscleGroup: 'Triceps', equipment: 'Élastique' },
  { id: 'bench-dips', name: 'Bench Dips', muscleGroup: 'Triceps', equipment: 'Poids du corps' },
  { id: 'bench-press-powerlifting', name: 'Bench Press - Powerlifting', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'bench-press-with-chains', name: 'Bench Press with Chains', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'board-press', name: 'Board Press', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'body-tricep-press', name: 'Body Tricep Press', muscleGroup: 'Triceps', equipment: 'Poids du corps' },
  { id: 'body-up', name: 'Body-Up', muscleGroup: 'Triceps', equipment: 'Poids du corps' },
  { id: 'cable-incline-triceps-extension', name: 'Cable Incline Triceps Extension', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'cable-lying-triceps-extension', name: 'Cable Lying Triceps Extension', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'cable-one-arm-tricep-extension', name: 'Cable One Arm Tricep Extension', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'cable-rope-overhead-triceps-extension', name: 'Cable Rope Overhead Triceps Extension', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'chain-handle-extension', name: 'Chain Handle Extension', muscleGroup: 'Triceps', equipment: 'Autre' },
  { id: 'close-grip-barbell-bench-press', name: 'Close-Grip Barbell Bench Press', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'close-grip-dumbbell-press', name: 'Close-Grip Dumbbell Press', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'close-grip-ez-bar-press', name: 'Close-Grip EZ-Bar Press', muscleGroup: 'Triceps', equipment: 'Barre EZ' },
  { id: 'close-grip-push-up-off-of-a-dumbbell', name: 'Close-Grip Push-Up off of a Dumbbell', muscleGroup: 'Triceps', equipment: 'Poids du corps' },
  { id: 'decline-close-grip-bench-to-skull-crusher', name: 'Decline Close-Grip Bench To Skull Crusher', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'decline-dumbbell-triceps-extension', name: 'Decline Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'decline-ez-bar-triceps-extension', name: 'Decline EZ Bar Triceps Extension', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'dip-machine', name: 'Dip Machine', muscleGroup: 'Triceps', equipment: 'Machine' },
  { id: 'dips-triceps-version', name: 'Dips - Triceps Version', muscleGroup: 'Triceps', equipment: 'Poids du corps' },
  { id: 'dumbbell-floor-press', name: 'Dumbbell Floor Press', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'dumbbell-one-arm-triceps-extension', name: 'Dumbbell One-Arm Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'dumbbell-tricep-extension-pronated-grip', name: 'Dumbbell Tricep Extension -Pronated Grip', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'ez-bar-skullcrusher', name: 'EZ-Bar Skullcrusher', muscleGroup: 'Triceps', equipment: 'Barre EZ' },
  { id: 'floor-press', name: 'Floor Press', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'floor-press-with-chains', name: 'Floor Press with Chains', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'incline-barbell-triceps-extension', name: 'Incline Barbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'incline-push-up-close-grip', name: 'Incline Push-Up Close-Grip', muscleGroup: 'Triceps', equipment: 'Poids du corps' },
  { id: 'jm-press', name: 'JM Press', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'kneeling-cable-triceps-extension', name: 'Kneeling Cable Triceps Extension', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'low-cable-triceps-extension', name: 'Low Cable Triceps Extension', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'lying-close-grip-barbell-triceps-extension-behind-the-head', name: 'Lying Close-Grip Barbell Triceps Extension Behind The Head', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'lying-close-grip-barbell-triceps-press-to-chin', name: 'Lying Close-Grip Barbell Triceps Press To Chin', muscleGroup: 'Triceps', equipment: 'Barre EZ' },
  { id: 'lying-dumbbell-tricep-extension', name: 'Lying Dumbbell Tricep Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'lying-triceps-press', name: 'Lying Triceps Press', muscleGroup: 'Triceps', equipment: 'Barre EZ' },
  { id: 'machine-triceps-extension', name: 'Machine Triceps Extension', muscleGroup: 'Triceps', equipment: 'Machine' },
  { id: 'one-arm-floor-press', name: 'One Arm Floor Press', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'one-arm-pronated-dumbbell-triceps-extension', name: 'One Arm Pronated Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'one-arm-supinated-dumbbell-triceps-extension', name: 'One Arm Supinated Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'parallel-bar-dip', name: 'Parallel Bar Dip', muscleGroup: 'Triceps', equipment: 'Autre' },
  { id: 'pin-presses', name: 'Pin Presses', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'push-ups-close-triceps-position', name: 'Push-Ups - Close Triceps Position', muscleGroup: 'Triceps', equipment: 'Poids du corps' },
  { id: 'reverse-band-bench-press', name: 'Reverse Band Bench Press', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'reverse-grip-triceps-pushdown', name: 'Reverse Grip Triceps Pushdown', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'reverse-triceps-bench-press', name: 'Reverse Triceps Bench Press', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'ring-dips', name: 'Ring Dips', muscleGroup: 'Triceps', equipment: 'Autre' },
  { id: 'seated-bent-over-one-arm-dumbbell-triceps-extension', name: 'Seated Bent-Over One-Arm Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'seated-bent-over-two-arm-dumbbell-triceps-extension', name: 'Seated Bent-Over Two-Arm Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'seated-triceps-press', name: 'Seated Triceps Press', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'sled-overhead-triceps-extension', name: 'Sled Overhead Triceps Extension', muscleGroup: 'Triceps', equipment: 'Autre' },
  { id: 'smith-machine-close-grip-bench-press', name: 'Smith Machine Close-Grip Bench Press', muscleGroup: 'Triceps', equipment: 'Machine' },
  { id: 'speed-band-overhead-triceps', name: 'Speed Band Overhead Triceps', muscleGroup: 'Triceps', equipment: 'Élastique' },
  { id: 'standing-bent-over-one-arm-dumbbell-triceps-extension', name: 'Standing Bent-Over One-Arm Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'standing-bent-over-two-arm-dumbbell-triceps-extension', name: 'Standing Bent-Over Two-Arm Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'standing-dumbbell-triceps-extension', name: 'Standing Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'standing-low-pulley-one-arm-triceps-extension', name: 'Standing Low-Pulley One-Arm Triceps Extension', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'standing-one-arm-dumbbell-triceps-extension', name: 'Standing One-Arm Dumbbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'standing-overhead-barbell-triceps-extension', name: 'Standing Overhead Barbell Triceps Extension', muscleGroup: 'Triceps', equipment: 'Barre' },
  { id: 'standing-towel-triceps-extension', name: 'Standing Towel Triceps Extension', muscleGroup: 'Triceps', equipment: 'Poids du corps' },
  { id: 'tate-press', name: 'Tate Press', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'tricep-dumbbell-kickback', name: 'Tricep Dumbbell Kickback', muscleGroup: 'Triceps', equipment: 'Haltères' },
  { id: 'triceps-overhead-extension-with-rope', name: 'Triceps Overhead Extension with Rope', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'triceps-pushdown', name: 'Triceps Pushdown', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'triceps-pushdown-rope-attachment', name: 'Triceps Pushdown - Rope Attachment', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'triceps-pushdown-v-bar-attachment', name: 'Triceps Pushdown - V-Bar Attachment', muscleGroup: 'Triceps', equipment: 'Poulie' },
  { id: 'weighted-bench-dip', name: 'Weighted Bench Dip', muscleGroup: 'Triceps', equipment: 'Autre' },
  { id: 'alternating-cable-shoulder-press', name: 'Alternating Cable Shoulder Press', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'alternating-deltoid-raise', name: 'Alternating Deltoid Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'alternating-kettlebell-press', name: 'Alternating Kettlebell Press', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'anti-gravity-press', name: 'Anti-Gravity Press', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'arnold-dumbbell-press', name: 'Arnold Dumbbell Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'back-flyes-with-bands', name: 'Back Flyes - With Bands', muscleGroup: 'Épaules', equipment: 'Élastique' },
  { id: 'band-pull-apart', name: 'Band Pull Apart', muscleGroup: 'Épaules', equipment: 'Élastique' },
  { id: 'barbell-incline-shoulder-raise', name: 'Barbell Incline Shoulder Raise', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'barbell-rear-delt-row', name: 'Barbell Rear Delt Row', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'barbell-shoulder-press', name: 'Barbell Shoulder Press', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'battling-ropes', name: 'Battling Ropes', muscleGroup: 'Épaules', equipment: 'Autre' },
  { id: 'bent-over-dumbbell-rear-delt-raise-with-head-on-bench', name: 'Bent Over Dumbbell Rear Delt Raise With Head On Bench', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'bent-over-low-pulley-side-lateral', name: 'Bent Over Low-Pulley Side Lateral', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'bradford-rocky-presses', name: 'Bradford/Rocky Presses', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'cable-internal-rotation', name: 'Cable Internal Rotation', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'cable-rear-delt-fly', name: 'Cable Rear Delt Fly', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'cable-rope-rear-delt-rows', name: 'Cable Rope Rear-Delt Rows', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'cable-seated-lateral-raise', name: 'Cable Seated Lateral Raise', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'cable-shoulder-press', name: 'Cable Shoulder Press', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'car-drivers', name: 'Car Drivers', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'circus-bell', name: 'Circus Bell', muscleGroup: 'Épaules', equipment: 'Autre' },
  { id: 'clean-and-jerk', name: 'Clean and Jerk', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'clean-and-press', name: 'Clean and Press', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'crucifix', name: 'Crucifix', muscleGroup: 'Épaules', equipment: 'Autre' },
  { id: 'cuban-press', name: 'Cuban Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'double-kettlebell-jerk', name: 'Double Kettlebell Jerk', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'double-kettlebell-push-press', name: 'Double Kettlebell Push Press', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'double-kettlebell-snatch', name: 'Double Kettlebell Snatch', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'dumbbell-incline-shoulder-raise', name: 'Dumbbell Incline Shoulder Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'dumbbell-lying-one-arm-rear-lateral-raise', name: 'Dumbbell Lying One-Arm Rear Lateral Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'dumbbell-lying-rear-lateral-raise', name: 'Dumbbell Lying Rear Lateral Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'dumbbell-one-arm-shoulder-press', name: 'Dumbbell One-Arm Shoulder Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'dumbbell-one-arm-upright-row', name: 'Dumbbell One-Arm Upright Row', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'dumbbell-raise', name: 'Dumbbell Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'dumbbell-scaption', name: 'Dumbbell Scaption', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'dumbbell-shoulder-press', name: 'Dumbbell Shoulder Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'external-rotation', name: 'External Rotation', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'external-rotation-with-band', name: 'External Rotation with Band', muscleGroup: 'Épaules', equipment: 'Élastique' },
  { id: 'external-rotation-with-cable', name: 'External Rotation with Cable', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'face-pull', name: 'Face Pull', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'front-cable-raise', name: 'Front Cable Raise', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'front-dumbbell-raise', name: 'Front Dumbbell Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'front-incline-dumbbell-raise', name: 'Front Incline Dumbbell Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'front-plate-raise', name: 'Front Plate Raise', muscleGroup: 'Épaules', equipment: 'Autre' },
  { id: 'front-two-dumbbell-raise', name: 'Front Two-Dumbbell Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'handstand-push-ups', name: 'Handstand Push-Ups', muscleGroup: 'Épaules', equipment: 'Poids du corps' },
  { id: 'internal-rotation-with-band', name: 'Internal Rotation with Band', muscleGroup: 'Épaules', equipment: 'Élastique' },
  { id: 'iron-cross', name: 'Iron Cross', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'jerk-balance', name: 'Jerk Balance', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'kettlebell-arnold-press', name: 'Kettlebell Arnold Press', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'kettlebell-pirate-ships', name: 'Kettlebell Pirate Ships', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'kettlebell-seated-press', name: 'Kettlebell Seated Press', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'kettlebell-seesaw-press', name: 'Kettlebell Seesaw Press', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'kettlebell-thruster', name: 'Kettlebell Thruster', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'kettlebell-turkish-get-up-lunge-style', name: 'Kettlebell Turkish Get-Up (Lunge style)', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'kettlebell-turkish-get-up-squat-style', name: 'Kettlebell Turkish Get-Up (Squat style)', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'landmine-linear-jammer', name: 'Landmine Linear Jammer', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'lateral-raise-with-bands', name: 'Lateral Raise - With Bands', muscleGroup: 'Épaules', equipment: 'Élastique' },
  { id: 'leverage-shoulder-press', name: 'Leverage Shoulder Press', muscleGroup: 'Épaules', equipment: 'Machine' },
  { id: 'log-lift', name: 'Log Lift', muscleGroup: 'Épaules', equipment: 'Autre' },
  { id: 'low-pulley-row-to-neck', name: 'Low Pulley Row To Neck', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'lying-one-arm-lateral-raise', name: 'Lying One-Arm Lateral Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'lying-rear-delt-raise', name: 'Lying Rear Delt Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'machine-shoulder-military-press', name: 'Machine Shoulder (Military) Press', muscleGroup: 'Épaules', equipment: 'Machine' },
  { id: 'one-arm-incline-lateral-raise', name: 'One-Arm Incline Lateral Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'one-arm-kettlebell-clean-and-jerk', name: 'One-Arm Kettlebell Clean and Jerk', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'one-arm-kettlebell-jerk', name: 'One-Arm Kettlebell Jerk', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'one-arm-kettlebell-military-press-to-the-side', name: 'One-Arm Kettlebell Military Press To The Side', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'one-arm-kettlebell-para-press', name: 'One-Arm Kettlebell Para Press', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'one-arm-kettlebell-push-press', name: 'One-Arm Kettlebell Push Press', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'one-arm-kettlebell-snatch', name: 'One-Arm Kettlebell Snatch', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'one-arm-kettlebell-split-jerk', name: 'One-Arm Kettlebell Split Jerk', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'one-arm-kettlebell-split-snatch', name: 'One-Arm Kettlebell Split Snatch', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'one-arm-side-laterals', name: 'One-Arm Side Laterals', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'power-partials', name: 'Power Partials', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'push-press', name: 'Push Press', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'push-press-behind-the-neck', name: 'Push Press - Behind the Neck', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'rack-delivery', name: 'Rack Delivery', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'reverse-flyes', name: 'Reverse Flyes', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'reverse-flyes-with-external-rotation', name: 'Reverse Flyes With External Rotation', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'reverse-machine-flyes', name: 'Reverse Machine Flyes', muscleGroup: 'Épaules', equipment: 'Machine' },
  { id: 'seated-barbell-military-press', name: 'Seated Barbell Military Press', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'seated-bent-over-rear-delt-raise', name: 'Seated Bent-Over Rear Delt Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'seated-cable-shoulder-press', name: 'Seated Cable Shoulder Press', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'seated-dumbbell-press', name: 'Seated Dumbbell Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'seated-side-lateral-raise', name: 'Seated Side Lateral Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'see-saw-press-alternating-side-press', name: 'See-Saw Press (Alternating Side Press)', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'shoulder-press-with-bands', name: 'Shoulder Press - With Bands', muscleGroup: 'Épaules', equipment: 'Élastique' },
  { id: 'side-lateral-raise', name: 'Side Lateral Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'side-laterals-to-front-raise', name: 'Side Laterals to Front Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'single-dumbbell-raise', name: 'Single Dumbbell Raise', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'single-arm-linear-jammer', name: 'Single-Arm Linear Jammer', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'sled-overhead-backward-walk', name: 'Sled Overhead Backward Walk', muscleGroup: 'Épaules', equipment: 'Autre' },
  { id: 'sled-reverse-flye', name: 'Sled Reverse Flye', muscleGroup: 'Épaules', equipment: 'Autre' },
  { id: 'smith-incline-shoulder-raise', name: 'Smith Incline Shoulder Raise', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'smith-machine-one-arm-upright-row', name: 'Smith Machine One-Arm Upright Row', muscleGroup: 'Épaules', equipment: 'Machine' },
  { id: 'smith-machine-overhead-shoulder-press', name: 'Smith Machine Overhead Shoulder Press', muscleGroup: 'Épaules', equipment: 'Machine' },
  { id: 'standing-alternating-dumbbell-press', name: 'Standing Alternating Dumbbell Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'standing-barbell-press-behind-neck', name: 'Standing Barbell Press Behind Neck', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'standing-bradford-press', name: 'Standing Bradford Press', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'standing-dumbbell-press', name: 'Standing Dumbbell Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'standing-dumbbell-straight-arm-front-delt-raise-above-head', name: 'Standing Dumbbell Straight-Arm Front Delt Raise Above Head', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'standing-front-barbell-raise-over-head', name: 'Standing Front Barbell Raise Over Head', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'standing-low-pulley-deltoid-raise', name: 'Standing Low-Pulley Deltoid Raise', muscleGroup: 'Épaules', equipment: 'Poulie' },
  { id: 'standing-military-press', name: 'Standing Military Press', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'standing-palm-in-one-arm-dumbbell-press', name: 'Standing Palm-In One-Arm Dumbbell Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'standing-palms-in-dumbbell-press', name: 'Standing Palms-In Dumbbell Press', muscleGroup: 'Épaules', equipment: 'Haltères' },
  { id: 'straight-raises-on-incline-bench', name: 'Straight Raises on Incline Bench', muscleGroup: 'Épaules', equipment: 'Barre' },
  { id: 'two-arm-kettlebell-clean', name: 'Two-Arm Kettlebell Clean', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'two-arm-kettlebell-jerk', name: 'Two-Arm Kettlebell Jerk', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'two-arm-kettlebell-military-press', name: 'Two-Arm Kettlebell Military Press', muscleGroup: 'Épaules', equipment: 'Kettlebell' },
  { id: 'upright-barbell-row', name: 'Upright Barbell Row', muscleGroup: 'Épaules', equipment: 'Barre' },
]